
%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of .PipelineFISH() of /src/fish_analyses.py

    participant p1 as PipelineFISH()<br>:fish_analyses.py
    participant p2 as number_of_images_to_process<br>:ReadImages
    participant p3 as Utilities<br>:Utilities
    participant p4 as None<br>:BigFISH


	p1 ->>+ p2: 1: read()
	p2 -->>- p1: 1: return value
	p1 ->>+ p3: 2: make_it_a_list(channels_with_cytosol)
	p3 -->>- p1: 2: return value
	p1 ->>+ p3: 3: make_it_a_list(channels_with_nucleus)
	p3 -->>- p1: 3: return value
	p1 ->>+ p3: 4: make_it_a_list(channels_with_FISH)
	p3 -->>- p1: 4: return value
	p1 ->>+ p3: 5: calculate_sharpness(list_images, channels_with_FISH<br>H=channels_with_FISH,threshold=s<br>harpness_threshold)
	p3 -->>- p1: 5: return value
	p1 ->>+ p3: 6: calculate_sharpness(list_images, channels_with_FISH<br>H=channels_with_FISH,threshold=s<br>harpness_threshold)
	p3 -->>- p1: 6: return value
	p1 ->>+ p4: 7: detect()
	p4 -->>- p1: 7: return value
	p1 ->>+ p3: 8: create_list_thresholds_FISH(channels_with_FISH,threshold_fo<br>r_spot_detection)
	p3 ->>+ p3: 8.1: make_it_a_list(channels_with_FISH)
	p3 -->>- p3: 8.1: return value
	p3 -->>- p1: 8: return value
        